import arxiv
client = arxiv.Client()
search = arxiv.Search(query="quantum", max_results=1)
result = next(client.results(search))
print(f"Title: {result.title}")
print(f"Authors: {result.authors}")
print(f"Published: {result.published}")
print(f"Summary: {result.summary[:50]}...")
print(f"URL: {result.pdf_url}")
print(f"Short ID: {result.get_short_id()}")
